FROM python:3.11-slim

ENV APP_DIR=/deploy
WORKDIR ${APP_DIR}

COPY requirements.txt ${APP_DIR}/requirements.txt
RUN pip3 install --no-cache-dir --upgrade pip \
    && pip3 install --no-cache-dir -r ${APP_DIR}/requirements.txt

COPY . ${APP_DIR}

CMD ["python3", "counter/main.py"]
